#!/usr/bin/env python3
"""
HSG17 T0-to-Host LVV Formatter — Core Logic

Ported exactly from the reference lvv_portal_formatter_T0toHOST.

This module contains ONLY the pure formatting logic (no tkinter, no Streamlit).
It is intended to be imported by the Streamlit page (03_HSG17_T0_to_Host_LVV.py).

The output Excel it produces must be identical to what the reference script produces
on the same inputs (combined cutsheet + LV Portal validation result files).
"""

import os
import re
import sys
import warnings
from copy import copy

# Suppress the benign "Workbook contains no default style" UserWarning that
# openpyxl emits when reading files generated by some external tools.
warnings.filterwarnings(
    "ignore",
    message=r".*no default style.*",
    category=UserWarning,
    module=r"openpyxl\..*",
)

from openpyxl import load_workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter


# ---------------------------------------------------------------------------
# Generic helpers
# ---------------------------------------------------------------------------

def norm(v):
    return str(v).strip().lower() if v is not None else ""


def canon_slot(p):
    """slot.../port...-1 and -2 -> ...-1   ;   -3 and -4 -> ...-3"""
    if not p: return ""
    s = norm(p)
    m = re.match(r'^(.*-)(\d+)$', s)
    if m:
        base, num = m.group(1), int(m.group(2))
        if num in (1, 2): return base + "1"
        if num in (3, 4): return base + "3"
    return s


def canon_swp(p):
    """swpNs0/s1 -> swpNs0   ;   swpNs2/s3 -> swpNs2"""
    if not p: return ""
    s = norm(p)
    m = re.match(r'^(swp\d+s)(\d+)$', s)
    if m:
        base, num = m.group(1), int(m.group(2))
        return base + str(num - num % 2)
    return s


def snapshot_col(ws, col_idx):
    """Capture a column's values + cell formatting + width so it can be moved."""
    data = []
    for r in range(1, ws.max_row + 1):
        src = ws.cell(row=r, column=col_idx)
        data.append({
            'value': src.value,
            'font': copy(src.font),
            'fill': copy(src.fill),
            'alignment': copy(src.alignment),
            'border': copy(src.border),
            'number_format': src.number_format,
        })
    width = ws.column_dimensions[get_column_letter(col_idx)].width
    return data, width


def write_col(ws, col_idx, data, width):
    for r, d in enumerate(data, start=1):
        c = ws.cell(row=r, column=col_idx, value=d['value'])
        c.font = d['font']; c.fill = d['fill']
        c.alignment = d['alignment']; c.border = d['border']
        c.number_format = d['number_format']
    if width:
        ws.column_dimensions[get_column_letter(col_idx)].width = width


def find_sheet(wb, *candidates):
    """Return the first matching sheet name (case-insensitive, ignoring extra spaces)."""
    lookup = {re.sub(r'\s+', ' ', s.strip().lower()): s for s in wb.sheetnames}
    for c in candidates:
        key = re.sub(r'\s+', ' ', c.strip().lower())
        if key in lookup:
            return lookup[key]
    return None


# ---------------------------------------------------------------------------
# Combined cutsheet -> lookups
# ---------------------------------------------------------------------------

def _find_header_idx(header, name_options):
    """Return the 0-based index of the first header matching any of name_options
    (case-insensitive, whitespace-tolerant), or None if not found."""
    for opt in name_options:
        key = re.sub(r'\s+', ' ', str(opt).strip().lower())
        for i, h in enumerate(header):
            if h is None:
                continue
            if re.sub(r'\s+', ' ', str(h).strip().lower()) == key:
                return i
    return None


def build_combined_lookups(combined_path):
    """
    Reads the combined cutsheet's first sheet (any name) and builds 4 lookups:
        exact_A, pair_A keyed on (DeviceA, PortA)
        exact_B, pair_B keyed on (DeviceB, PortB)
    Columns are located BY HEADER NAME so the script tolerates layout
    variations (e.g. a missing FDF column).
    Returns (header_list, exact_A, pair_A, exact_B, pair_B).
    """
    wb = load_workbook(combined_path, read_only=True, data_only=True)
    ws = wb[wb.sheetnames[0]]

    header = None
    rows = []
    for i, row in enumerate(ws.iter_rows(values_only=True)):
        if i == 0:
            header = list(row)
        else:
            rows.append(row)

    # ---- Detect ALLCONNECTIONS format (e.g. QFABT0toHOST_allconnections) ----
    # Keys live in 'DeviceA Name'/'DeviceA Port' (compute side) and
    # 'DeviceB Name'/'DeviceB Port' (T0 switch side). The plain 'DeviceA'
    # column there is a combined "device + port" string, NOT the key.
    ac_a_dev  = _find_header_idx(header, ['DeviceA Name'])
    ac_a_port = _find_header_idx(header, ['DeviceA Port'])

    if ac_a_dev is not None and ac_a_port is not None:
        ac_b_dev  = _find_header_idx(header, ['DeviceB Name'])
        ac_b_port = _find_header_idx(header, ['DeviceB Port'])

        # Cable-path + label columns to carry into the report (in this order).
        # 'DeviceA'/'DeviceB' are renamed so they don't collide with the
        # populate() skip list (which drops 'DeviceA' for the legacy format).
        keep = [
            ('DeviceA',                 'DeviceA (Cutsheet)'),
            ('RackA',                   'RackA'),
            ('OHR',                     'OHR'),
            ('T0',                      'T0'),
            ('DeviceB',                 'DeviceB (Cutsheet)'),
            ('RackB',                   'RackB'),
            ('Source_port',             'Source_port'),
            ('Destination_port',        'Destination_port'),
            ('DeviceA Physical Port',   'DeviceA Physical Port'),
            ('DeviceB Physical Port',   'DeviceB Physical Port'),
            ('Cable Color',             'Cable Color'),
        ]
        keep_idx, out_header = [], []
        for src_name, out_name in keep:
            i = _find_header_idx(header, [src_name])
            if i is not None:
                keep_idx.append(i)
                out_header.append(out_name)

        exact_A, pair_A, exact_B, pair_B = {}, {}, {}, {}
        for r in rows:
            reduced = tuple(r[i] if i < len(r) else None for i in keep_idx)
            if ac_a_dev < len(r) and r[ac_a_dev]:
                port_val = r[ac_a_port] if ac_a_port < len(r) else None
                exact_A.setdefault((norm(r[ac_a_dev]), norm(port_val)), reduced)
                pair_A.setdefault((norm(r[ac_a_dev]), canon_slot(port_val)), reduced)
            if (ac_b_dev is not None and ac_b_port is not None
                    and ac_b_dev < len(r) and r[ac_b_dev]):
                port_val = r[ac_b_port] if ac_b_port < len(r) else None
                exact_B.setdefault((norm(r[ac_b_dev]), norm(port_val)), reduced)
                pair_B.setdefault((norm(r[ac_b_dev]), canon_swp(port_val)), reduced)
        return out_header, exact_A, pair_A, exact_B, pair_B

    # ---- Legacy COMBINED format (DeviceA/PortA/DeviceB/PortB) ----
    # Locate join-key columns by header name (not by position).
    a_dev_i  = _find_header_idx(header, ['DeviceA', 'Device A'])
    a_port_i = _find_header_idx(header, ['PortA', 'Port A'])
    b_dev_i  = _find_header_idx(header, ['DeviceB', 'Device B'])
    b_port_i = _find_header_idx(header, ['PortB', 'Port B'])

    if a_dev_i is None or a_port_i is None:
        raise ValueError(
            "Combined cutsheet is missing required A-side columns "
            "('DeviceA'+'PortA' or 'DeviceA Name'+'DeviceA Port'). "
            "Found headers: " + repr(header)
        )

    exact_A, pair_A, exact_B, pair_B = {}, {}, {}, {}
    for r in rows:
        if a_dev_i < len(r) and r[a_dev_i]:
            port_val = r[a_port_i] if a_port_i < len(r) else None
            exact_A.setdefault((norm(r[a_dev_i]), norm(port_val)), r)
            pair_A.setdefault((norm(r[a_dev_i]), canon_slot(port_val)), r)
        if (b_dev_i is not None and b_port_i is not None
                and b_dev_i < len(r) and r[b_dev_i]):
            port_val = r[b_port_i] if b_port_i < len(r) else None
            exact_B.setdefault((norm(r[b_dev_i]), norm(port_val)), r)
            pair_B.setdefault((norm(r[b_dev_i]), canon_swp(port_val)), r)
    return header, exact_A, pair_A, exact_B, pair_B


# ---------------------------------------------------------------------------
# Lookup-and-populate
# ---------------------------------------------------------------------------

def get_header_style(ws):
    src = ws.cell(row=1, column=1)
    return {
        'font': copy(src.font), 'fill': copy(src.fill),
        'alignment': copy(src.alignment), 'border': copy(src.border),
    }

# Headers from the combined cutsheet that are ALSO the worksheet's join keys
# (DeviceA/PortA), so they shouldn't be re-emitted when we append match data.
DEFAULT_SKIP_HEADERS = ('DeviceA', 'Device A', 'PortA', 'Port A')

def populate(ws, key_name_col, key_port_col,
             exact_lookup, pair_lookup, canon_fn,
             combined_header, skip_headers=DEFAULT_SKIP_HEADERS,
             header_suffix=""):
    """Append combined-sheet columns (minus skip_headers) into ws, populating by
    lookup. Columns to skip are matched by HEADER NAME so it works regardless
    of how many columns the cutsheet has."""
    header = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column + 1)]
    name_idx = header.index(key_name_col) + 1
    port_idx = header.index(key_port_col) + 1

    skip_norm = {re.sub(r'\s+', ' ', str(s).strip().lower()) for s in skip_headers}
    add_indices = [
        i for i, h in enumerate(combined_header)
        if h is not None
        and re.sub(r'\s+', ' ', str(h).strip().lower()) not in skip_norm
    ]
    add_headers = [f"{combined_header[i]}{header_suffix}" for i in add_indices]

    start_col = ws.max_column + 1
    hstyle = get_header_style(ws)
    for off, h in enumerate(add_headers):
        c = ws.cell(row=1, column=start_col + off, value=h)
        c.font = hstyle['font']; c.fill = hstyle['fill']
        c.alignment = hstyle['alignment']; c.border = hstyle['border']

    matched_exact = matched_pair = unmatched = 0
    for r in range(2, ws.max_row + 1):
        nv = ws.cell(row=r, column=name_idx).value
        pv = ws.cell(row=r, column=port_idx).value
        nkey = norm(nv)
        match = exact_lookup.get((nkey, norm(pv)))
        used_pair = False
        if not match:
            match = pair_lookup.get((nkey, canon_fn(pv)))
            used_pair = bool(match)
        if match:
            if used_pair: matched_pair += 1
            else:         matched_exact += 1
            for off, idx in enumerate(add_indices):
                val = match[idx] if idx < len(match) else None
                ws.cell(row=r, column=start_col + off, value=val)
        else:
            unmatched += 1
    return matched_exact, matched_pair, unmatched


# ---------------------------------------------------------------------------
# Per-sheet transformations
# ---------------------------------------------------------------------------

def mark_ct_off(ws, key_col_name='Remote Device Name',
                threshold=16, note_text='maybe CT off',
                grey_color='A6A6A6'):
    """
    Count occurrences of `key_col_name` across data rows. For each row whose
    value appears exactly `threshold` times, set whole-row font to grey and
    write `note_text` into the Note column (created at the back if missing).
    """
    header = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column+1)]
    if key_col_name not in header:
        return 0
    key_idx = header.index(key_col_name) + 1

    if 'Note' not in header:
        # add_note_column is defined later in this module; safe at call time
        new_col = ws.max_column + 1
        src = ws.cell(row=1, column=1)
        cell = ws.cell(row=1, column=new_col, value='Note')
        cell.font = copy(src.font); cell.fill = copy(src.fill)
        cell.alignment = copy(src.alignment); cell.border = copy(src.border)
        ws.column_dimensions[get_column_letter(new_col)].width = 30
        header = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column+1)]
    note_idx = header.index('Note') + 1

    from collections import Counter
    counts = Counter()
    for r in range(2, ws.max_row + 1):
        v = ws.cell(row=r, column=key_idx).value
        if v: counts[str(v).strip()] += 1
    targets = {k for k, c in counts.items() if c == threshold}

    marked = 0
    for r in range(2, ws.max_row + 1):
        v = ws.cell(row=r, column=key_idx).value
        if v and str(v).strip() in targets:
            for c in range(1, ws.max_column + 1):
                cell = ws.cell(row=r, column=c)
                f = cell.font
                cell.font = Font(
                    name=f.name, size=f.size, bold=f.bold, italic=f.italic,
                    vertAlign=f.vertAlign, underline=f.underline, strike=f.strike,
                    color=grey_color, family=f.family, scheme=f.scheme
                )
            ws.cell(row=r, column=note_idx, value=note_text)
            marked += 1
    return marked


def process_lldp(wb, combined):
    combined_header, exact_A, pair_A, exact_B, pair_B = combined
    sheet = find_sheet(wb, "LLDP Mismatch + Link Down (GPU)", "LLDP Mismatch  (GPU)", "LLDP Mismatch (GPU)")
    if not sheet:
        return None
    ws = wb[sheet]

    # 1) drop rows where either:
    #    (a) Current D/E/F are all "missing"            (Observed remote: missing:missing)
    #    (b) Current Device B Name does NOT contain "compute"
    #        i.e. Observed remote is a serial/number (e.g. 2610QA11K9) instead
    #        of a real compute host (jbp19-...-computeN). Only true compute-to-
    #        compute mismatches are kept for review.
    cols = {h: i+1 for i, h in enumerate(ws.cell(row=1, column=c).value for c in range(1, ws.max_column+1))}
    cn = cols.get('Current Device B Name')
    cl = cols.get('Current B Location')
    cp = cols.get('Current Device B Port')
    if cn and cl and cp:
        rows_to_drop = []
        for r in range(2, ws.max_row + 1):
            # (a) all three current fields literally "missing"
            all_missing = all(norm(ws.cell(row=r, column=c).value) == "missing"
                              for c in (cn, cl, cp))
            # (b) Current Device B Name has a value but doesn't contain "compute"
            cn_val = ws.cell(row=r, column=cn).value
            not_compute = (
                cn_val is not None
                and str(cn_val).strip() != ""
                and "compute" not in str(cn_val).lower()
            )
            # (c) Current Device B Port is a MAC address (e.g. 08:20:e7:9c:c7:8e)
            #     — LLDP reported the neighbour's port ID as a MAC instead of a
            #     named interface; the MAC varies per device, so match the format.
            cp_val = ws.cell(row=r, column=cp).value
            port_is_mac = bool(
                cp_val is not None
                and re.fullmatch(
                    r'(?:[0-9a-fA-F]{2}[:-]){5}[0-9a-fA-F]{2}',
                    str(cp_val).strip()
                )
            )
            if all_missing or not_compute or port_is_mac:
                rows_to_drop.append(r)
        for r in reversed(rows_to_drop):
            ws.delete_rows(r, 1)

    # 2) rename sheet
    new_name = "Mismatch"
    if sheet != new_name:
        ws.title = new_name

    # 3) populate Expected-side lookup
    populate(ws, 'Expected Device B Name', 'Expected Device B Port',
             exact_A, pair_A, canon_slot, combined_header)

    # 4) remove unwanted columns
    to_remove = ['Device A Name', 'Device A Location', 'Device A Port',
                 'Current B Location', 'Expected B Location',
                 'Patch Panel Matrix', 'Error Message']
    drop_cols_by_name(ws, to_remove)

    # 5) populate Current-side lookup (suffix " (Current)")
    populate(ws, 'Current Device B Name', 'Current Device B Port',
             exact_A, pair_A, canon_slot, combined_header,
             header_suffix=" (Current)")

    # 6) reverse Current columns
    header = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column+1)]
    current_cols = [h for h in header if 'current' in str(h).lower()]
    reversed_current = list(reversed(current_cols))
    new_order = []
    ci = 0
    for h in header:
        if 'current' in str(h).lower():
            new_order.append(reversed_current[ci]); ci += 1
        else:
            new_order.append(h)
    reorder_columns(ws, new_order)

    # 7) move all white (non-Current) columns to the front, pink Current to the back
    header = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column+1)]
    white = [h for h in header if 'current' not in str(h).lower()]
    pink  = [h for h in header if 'current' in str(h).lower()]
    reorder_columns(ws, white + pink)

    # 8) pink fill on every Current column (header + data)
    pink_fill = PatternFill(start_color='FFC0CB', end_color='FFC0CB', fill_type='solid')
    header = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column+1)]
    for ci, h in enumerate(header, start=1):
        if 'current' in str(h).lower():
            for r in range(1, ws.max_row + 1):
                ws.cell(row=r, column=ci).fill = pink_fill

    return ws.title


def process_optic(wb, combined):
    combined_header, exact_A, pair_A, exact_B, pair_B = combined
    gpu  = find_sheet(wb, "Optic Errors (GPU)", "Optic Errors")
    host = find_sheet(wb, "Optic Errors (Host)")
    if not gpu and not host:
        return None

    if gpu:
        sheet = gpu
        ws = wb[sheet]
        # 0) combine the Host optic tab into this one, then delete it so both are
        #    formatted together. NOTE: in the Host tab the compute device (the
        #    side that matches the cutsheet) lives in Source Device Name/Port,
        #    whereas in the GPU tab it lives in Remote Device Name/Port. So host
        #    Source Name/Port are mapped into the combined Remote columns — this
        #    makes the single Remote-keyed lookup match host rows on their Source.
        if host and host != sheet:
            hws = wb[host]
            gpu_hdr = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column+1)]
            host_hdr = [hws.cell(row=1, column=c).value for c in range(1, hws.max_column+1)]
            col_of = {h: i + 1 for i, h in enumerate(gpu_hdr)}
            hidx = {h: i + 1 for i, h in enumerate(host_hdr)}

            def hval(r, name):
                return hws.cell(row=r, column=hidx[name]).value if name in hidx else None

            dest = ws.max_row + 1
            for r in range(2, hws.max_row + 1):
                if all(hws.cell(row=r, column=c).value in (None, "")
                       for c in range(1, hws.max_column + 1)):
                    continue
                # remap: Source (host) -> Remote (combined) so the lookup matches
                remap = {
                    'Remote Device Name': hval(r, 'Source Device Name'),
                    'Remote Device Port': hval(r, 'Source Device Port'),
                    'Rx Power':           hval(r, 'Rx Power'),
                    'Patch Panel Matrix': hval(r, 'Patch Panel Matrix'),
                }
                for h, val in remap.items():
                    if h in col_of:
                        ws.cell(row=dest, column=col_of[h], value=val)
                dest += 1
            del wb[host]
    else:
        # Host-only input: use the Host tab as the base. Remap its own Source
        # Name/Port into the Remote columns in place so the Remote-keyed lookup
        # still matches on the compute device.
        sheet = host
        ws = wb[sheet]
        hdr = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column+1)]
        hidx = {h: i + 1 for i, h in enumerate(hdr)}
        if 'Source Device Name' in hidx and 'Remote Device Name' in hidx:
            for r in range(2, ws.max_row + 1):
                ws.cell(row=r, column=hidx['Remote Device Name'],
                        value=ws.cell(row=r, column=hidx['Source Device Name']).value)
                if 'Source Device Port' in hidx and 'Remote Device Port' in hidx:
                    ws.cell(row=r, column=hidx['Remote Device Port'],
                            value=ws.cell(row=r, column=hidx['Source Device Port']).value)


    # 1) drop rows where Rx Power contains "missing"
    header = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column+1)]
    rx_idx = header.index('Rx Power') + 1
    to_drop = []
    for r in range(2, ws.max_row + 1):
        v = ws.cell(row=r, column=rx_idx).value
        if v is not None and "missing" in str(v).lower():
            to_drop.append(r)
    for r in reversed(to_drop):
        ws.delete_rows(r, 1)

    # 2) populate via DeviceA/PortA lookup (matched on Remote Device Name + Remote Device Port)
    populate(ws, 'Remote Device Name', 'Remote Device Port',
             exact_A, pair_A, canon_slot, combined_header)

    # 3) drop unwanted columns (Source side is dropped; Remote side is kept as the match key)
    drop_cols_by_name(ws, ['Source Device Name', 'Source Device Location', 'Source Device Port'])

    # 4) remove Patch Panel Matrix and move Rx Power to front
    drop_cols_by_name(ws, ['Patch Panel Matrix', 'Error Message'])
    header = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column+1)]
    if header[0] != 'Rx Power' and 'Rx Power' in header:
        rx_idx = header.index('Rx Power') + 1
        data, width = snapshot_col(ws, rx_idx)
        ws.delete_cols(rx_idx, 1)
        ws.insert_cols(1)
        write_col(ws, 1, data, width)

    # 5) light grey fill on Rx Power cells where all instant values are -40, and grey font on whole row
    grey_fill = PatternFill(start_color='E0E0E0', end_color='E0E0E0', fill_type='solid')
    grey_color = 'A6A6A6'
    header = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column+1)]
    rx_idx = header.index('Rx Power') + 1
    for r in range(2, ws.max_row + 1):
        v = ws.cell(row=r, column=rx_idx).value
        s = str(v) if v is not None else ""
        nums = re.findall(r'instant:\s*(-?\d+(?:\.\d+)?)', s)
        if not nums:
            # Host rows store a bare reading (e.g. "-40.0") with no "instant:" prefix
            nums = re.findall(r'-?\d+(?:\.\d+)?', s)
        if nums and all(abs(float(n) - (-40.0)) < 1e-9 for n in nums):
            ws.cell(row=r, column=rx_idx).fill = grey_fill
            for c in range(1, ws.max_column + 1):
                cell = ws.cell(row=r, column=c)
                f = cell.font
                cell.font = Font(
                    name=f.name, size=f.size, bold=f.bold, italic=f.italic,
                    vertAlign=f.vertAlign, underline=f.underline, strike=f.strike,
                    color=grey_color, family=f.family, scheme=f.scheme
                )

    # 6) "Maybe CT off" — devices that appear exactly 16 times: grey row + Note
    mark_ct_off(ws, key_col_name='Remote Device Name', threshold=16, note_text='maybe CT off')

    # 6b) cross-reference Interface Down: if the same link (Remote Device Name +
    #     Remote Device Port) also appears there, light-grey the row font and
    #     note "also interface down".
    ifd = find_sheet(wb, "Interface Down Errors", "Interface Down Errors (GPU)")
    if ifd:
        iws = wb[ifd]
        ih = [iws.cell(row=1, column=c).value for c in range(1, iws.max_column+1)]
        if 'Remote Device Name' in ih and 'Remote Device Port' in ih:
            ni = ih.index('Remote Device Name') + 1
            pi = ih.index('Remote Device Port') + 1
            ifd_links = set()
            for r in range(2, iws.max_row + 1):
                nm = iws.cell(row=r, column=ni).value
                if nm:
                    ifd_links.add((norm(nm), norm(iws.cell(row=r, column=pi).value)))

            header = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column+1)]
            if 'Note' not in header:
                add_note_column(ws)
                header = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column+1)]
            rn_idx = header.index('Remote Device Name') + 1
            rp_idx = header.index('Remote Device Port') + 1
            note_idx = header.index('Note') + 1
            for r in range(2, ws.max_row + 1):
                key = (norm(ws.cell(row=r, column=rn_idx).value),
                       norm(ws.cell(row=r, column=rp_idx).value))
                if key in ifd_links:
                    for c in range(1, ws.max_column + 1):
                        cell = ws.cell(row=r, column=c)
                        f = cell.font
                        cell.font = Font(
                            name=f.name, size=f.size, bold=f.bold, italic=f.italic,
                            vertAlign=f.vertAlign, underline=f.underline, strike=f.strike,
                            color='A6A6A6', family=f.family, scheme=f.scheme
                        )
                    ws.cell(row=r, column=note_idx, value='also interface down')

    # 7) rename combined tab
    if ws.title != "Optic Errors":
        ws.title = "Optic Errors"

    return ws.title


def process_fec(wb, combined):
    combined_header, exact_A, pair_A, exact_B, pair_B = combined
    sheet = find_sheet(wb, "FEC_BER Errors (GPU)")
    if not sheet:
        return None
    ws = wb[sheet]
    populate(ws, 'Device Name', 'Interface',
             exact_A, pair_A, canon_slot, combined_header)
    drop_cols_by_name(ws, ['Lane Values', 'Patch Panel Matrix'])
    # move Issue to the front (if present)
    header = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column+1)]
    if 'Issue' in header and header[0] != 'Issue':
        idx = header.index('Issue') + 1
        data, width = snapshot_col(ws, idx)
        ws.delete_cols(idx, 1)
        ws.insert_cols(1)
        write_col(ws, 1, data, width)
    return ws.title


def process_interface_down(wb, combined):
    combined_header, exact_A, pair_A, exact_B, pair_B = combined
    sheet = find_sheet(wb, "Interface Down Errors (GPU)")
    if not sheet:
        return None
    ws = wb[sheet]
    populate(ws, 'Remote Device Name', 'Remote Device Port',
             exact_A, pair_A, canon_slot, combined_header)
    drop_cols_by_name(ws, [
        'Source Device Name', 'Source Device Location', 'Source Device Port',
        'Issue', 'Patch Panel Matrix', 'Error Message'
    ])
    # "Maybe CT off" — devices appearing exactly 16 times: grey row + Note
    mark_ct_off(ws, key_col_name='Remote Device Name', threshold=16, note_text='maybe CT off')
    if ws.title != "Interface Down Errors":
        ws.title = "Interface Down Errors"
    return ws.title


def process_rawber(wb, combined):
    combined_header, exact_A, pair_A, exact_B, pair_B = combined
    gpu  = find_sheet(wb, "RAW_BER Errors (GPU)", "RAW_BER Errors", "Fec Errors")
    host = find_sheet(wb, "RAW_BER Errors (Host)")
    if not gpu and not host:
        return None

    grey_rows = []

    if gpu:
        sheet = gpu
        ws = wb[sheet]
        # 0) combine the Host RAW_BER tab into this one, then delete it. As with
        #    the optics, the compute device (the cutsheet-match side) lives in
        #    Source Device Name/Port on the host tab, so map those into the GPU
        #    tab's Device Name / Interface columns before matching.
        if host and host != sheet:
            hws = wb[host]
            gpu_hdr = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column+1)]
            host_hdr = [hws.cell(row=1, column=c).value for c in range(1, hws.max_column+1)]
            col_of = {h: i + 1 for i, h in enumerate(gpu_hdr)}
            hidx = {h: i + 1 for i, h in enumerate(host_hdr)}

            def hval(r, name):
                return hws.cell(row=r, column=hidx[name]).value if name in hidx else None

            dest = ws.max_row + 1
            for r in range(2, hws.max_row + 1):
                if all(hws.cell(row=r, column=c).value in (None, "")
                       for c in range(1, hws.max_column + 1)):
                    continue
                remap = {
                    'Device Name': hval(r, 'Source Device Name'),
                    'Interface':   hval(r, 'Source Device Port'),
                }
                for h, val in remap.items():
                    if h in col_of:
                        ws.cell(row=dest, column=col_of[h], value=val)
                # flag rows whose original Raw BER / Status read "Not Available" / "Missing"
                if norm(hval(r, 'Raw BER')) == 'not available' and norm(hval(r, 'Status')) == 'missing':
                    grey_rows.append(dest)
                dest += 1
            del wb[host]
    else:
        # Host-only input: rebuild the Host tab into a [Device Name, Interface]
        # base (Source Name/Port = the compute side), then match the same way.
        sheet = host
        ws = wb[sheet]
        hdr = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column+1)]
        hidx = {h: i + 1 for i, h in enumerate(hdr)}

        def hv(r, name):
            return ws.cell(row=r, column=hidx[name]).value if name in hidx else None

        extracted = []
        for r in range(2, ws.max_row + 1):
            if all(ws.cell(row=r, column=c).value in (None, "")
                   for c in range(1, ws.max_column + 1)):
                continue
            grey = (norm(hv(r, 'Raw BER')) == 'not available'
                    and norm(hv(r, 'Status')) == 'missing')
            extracted.append((hv(r, 'Source Device Name'), hv(r, 'Source Device Port'), grey))

        ws.delete_cols(1, ws.max_column)
        ws.cell(row=1, column=1, value='Device Name')
        ws.cell(row=1, column=2, value='Interface')
        for i, (dn, it, grey) in enumerate(extracted, start=2):
            ws.cell(row=i, column=1, value=dn)
            ws.cell(row=i, column=2, value=it)
            if grey:
                grey_rows.append(i)

    # 1) match & populate via Device Name + Interface
    populate(ws, 'Device Name', 'Interface',
             exact_A, pair_A, canon_slot, combined_header)

    # 2) remove unwanted columns
    drop_cols_by_name(ws, ['Lane Values', 'Issue', 'Patch Panel Matrix', 'Error Message'])

    # 2b) light-grey the font on host rows that were "Not Available" / "Missing",
    #     and note "not available" on those rows.
    grey_color = 'A6A6A6'
    if grey_rows:
        header = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column+1)]
        if 'Note' not in header:
            add_note_column(ws)
            header = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column+1)]
        note_idx = header.index('Note') + 1
        for r in grey_rows:
            for c in range(1, ws.max_column + 1):
                cell = ws.cell(row=r, column=c)
                f = cell.font
                cell.font = Font(
                    name=f.name, size=f.size, bold=f.bold, italic=f.italic,
                    vertAlign=f.vertAlign, underline=f.underline, strike=f.strike,
                    color=grey_color, family=f.family, scheme=f.scheme
                )
            ws.cell(row=r, column=note_idx, value='not available')

    # 2c) cross-reference Optic Errors: if the same link (Device Name +
    #     Interface here == Remote Device Name + Remote Device Port there)
    #     also appears in the Optic Errors tab, light-grey the row font and
    #     note "also optic error".
    optic = find_sheet(wb, "Optic Errors", "Optic Errors (GPU)")
    if optic:
        ows = wb[optic]
        oh = [ows.cell(row=1, column=c).value for c in range(1, ows.max_column+1)]
        if 'Remote Device Name' in oh and 'Remote Device Port' in oh:
            oni = oh.index('Remote Device Name') + 1
            opi = oh.index('Remote Device Port') + 1
            optic_links = set()
            for r in range(2, ows.max_row + 1):
                nm = ows.cell(row=r, column=oni).value
                if nm:
                    optic_links.add((norm(nm), norm(ows.cell(row=r, column=opi).value)))

            header = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column+1)]
            if 'Device Name' in header and 'Interface' in header:
                if 'Note' not in header:
                    add_note_column(ws)
                    header = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column+1)]
                dn_idx = header.index('Device Name') + 1
                it_idx = header.index('Interface') + 1
                note_idx = header.index('Note') + 1
                for r in range(2, ws.max_row + 1):
                    key = (norm(ws.cell(row=r, column=dn_idx).value),
                           norm(ws.cell(row=r, column=it_idx).value))
                    if key in optic_links:
                        for c in range(1, ws.max_column + 1):
                            cell = ws.cell(row=r, column=c)
                            f = cell.font
                            cell.font = Font(
                                name=f.name, size=f.size, bold=f.bold, italic=f.italic,
                                vertAlign=f.vertAlign, underline=f.underline, strike=f.strike,
                                color=grey_color, family=f.family, scheme=f.scheme
                            )
                        ws.cell(row=r, column=note_idx, value='also optic error')

    # 3) rename combined tab
    if ws.title != "Fec Errors":
        ws.title = "Fec Errors"

    return ws.title


def process_lldp_missing(wb, combined):
    combined_header, exact_A, pair_A, exact_B, pair_B = combined
    sheet = find_sheet(wb, "LLDP Missing (GPU)", "LLDP Missing  (GPU)")
    if not sheet:
        return None
    ws = wb[sheet]

    # 1) match & populate via Expected Device B Name + Expected Device B Port
    populate(ws, 'Expected Device B Name', 'Expected Device B Port',
             exact_A, pair_A, canon_slot, combined_header)

    # 2) keep Error Message + Expected Device B Name/Port (+ the appended cutsheet
    #    columns); drop the rest. The Note column is added later by
    #    apply_workbook_formatting, so it is preserved automatically.
    drop_cols_by_name(ws, [
        'Device A Name', 'Device A Location', 'Device A Port',
        'Current Device B Name', 'Current B Location', 'Current Device B Port',
        'Expected B Location',
        'Patch Panel Matrix',
    ])

    # 3) order: Error Message, Expected Device B Name, Expected Device B Port,
    #    then the populated cutsheet columns
    header = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column+1)]
    lead = [h for h in ('Error Message', 'Expected Device B Name',
                        'Expected Device B Port') if h in header]
    rest = [h for h in header if h not in lead]
    reorder_columns(ws, lead + rest)

    # 4) trim Error Message: keep only from "Observed remote" onward
    header = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column+1)]
    if 'Error Message' in header:
        em_idx = header.index('Error Message') + 1
        for r in range(2, ws.max_row + 1):
            v = ws.cell(row=r, column=em_idx).value
            if v is None:
                continue
            s = str(v)
            pos = s.find('Observed remote')
            if pos != -1:
                ws.cell(row=r, column=em_idx, value=s[pos:])

    # 5) rename tab
    if ws.title != "LLDP missing (IGNORE)":
        ws.title = "LLDP missing (IGNORE)"

    return ws.title


# ---------------------------------------------------------------------------
# Column ops
# ---------------------------------------------------------------------------

def drop_cols_by_name(ws, names):
    header = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column+1)]
    indices = sorted([header.index(n) + 1 for n in names if n in header], reverse=True)
    for idx in indices:
        ws.delete_cols(idx, 1)

def reorder_columns(ws, new_order):
    """Reorder columns of ws to match new_order (list of header names that already exist)."""
    header = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column+1)]
    snapshots = {h: snapshot_col(ws, header.index(h) + 1) for h in header}
    ws.delete_cols(1, ws.max_column)
    for new_idx, name in enumerate(new_order, start=1):
        data, width = snapshots[name]
        write_col(ws, new_idx, data, width)


# ---------------------------------------------------------------------------
# Sheet-wide / workbook-wide formatting
# ---------------------------------------------------------------------------

def add_note_column(ws):
    new_col = ws.max_column + 1
    src = ws.cell(row=1, column=1)
    cell = ws.cell(row=1, column=new_col, value='Note')
    cell.font = copy(src.font); cell.fill = copy(src.fill)
    cell.alignment = copy(src.alignment); cell.border = copy(src.border)
    ws.column_dimensions[get_column_letter(new_col)].width = 30

def update_summary(wb):
    sheet = find_sheet(wb, "Summary")
    if not sheet:
        return
    ws = wb[sheet]
    existing_sheets = set(wb.sheetnames)

    name_map = {
        'lldp mismatch + link down (gpu)': find_sheet(wb, "Mismatch", "LLDP Mismatch  (GPU)", "LLDP Mismatch (GPU)"),
        'lldp mismatch  (gpu)':            find_sheet(wb, "Mismatch", "LLDP Mismatch  (GPU)", "LLDP Mismatch (GPU)"),
        'lldp mismatch (gpu)':             find_sheet(wb, "Mismatch", "LLDP Mismatch  (GPU)", "LLDP Mismatch (GPU)"),
        'optic errors (gpu)':              find_sheet(wb, "Optic Errors", "Optic Errors (GPU)"),
        'optic errors (host)':             find_sheet(wb, "Optic Errors", "Optic Errors (GPU)"),
        'lldp missing (gpu)':              None,
        'raw_ber errors (gpu)':            find_sheet(wb, "Fec Errors", "RAW_BER Errors", "RAW_BER Errors (GPU)"),
        'raw_ber errors (host)':           find_sheet(wb, "Fec Errors", "RAW_BER Errors", "RAW_BER Errors (GPU)"),
        'fec_ber errors (gpu)':            find_sheet(wb, "Fec Errors", "FEC_BER Errors (GPU)"),
        'interface down errors (gpu)':     find_sheet(wb, "Interface Down Errors", "Interface Down Errors (GPU)"),
    }

    # rebuild rows: keep only categories that map to a real sheet.
    # Count is the number of data rows whose font is NOT light grey (A6A6A6),
    # i.e. greyed rows (CT-off, -40 optics, "also interface down", host
    # "Not Available/Missing") are excluded from the count.
    def _is_grey(cell):
        col = cell.font.color if cell.font else None
        rgb = getattr(col, 'rgb', None)
        return isinstance(rgb, str) and rgb.upper().endswith('A6A6A6')

    def count_non_grey(tsheet):
        tws = wb[tsheet]
        n = 0
        for r in range(2, tws.max_row + 1):
            a = tws.cell(row=r, column=1)
            if a.value not in (None, "") and not _is_grey(a):
                n += 1
        return n

    rows_keep = [(ws.cell(row=1, column=1).value, ws.cell(row=1, column=2).value)]
    seen_targets = set()
    for r in range(2, ws.max_row + 1):
        cat = ws.cell(row=r, column=1).value
        target = name_map.get(norm(cat))
        if target and target in existing_sheets and target not in seen_targets:
            seen_targets.add(target)
            rows_keep.append((target, count_non_grey(target)))

    # append Total row that sums the category counts
    if len(rows_keep) > 1:
        first_data_row = 2
        last_data_row = len(rows_keep)
        rows_keep.append(("Total", f"=SUM(B{first_data_row}:B{last_data_row})"))

    # clear & rewrite
    for r in range(1, ws.max_row + 1):
        for c in range(1, ws.max_column + 1):
            ws.cell(row=r, column=c).value = None
    for i, (a, b) in enumerate(rows_keep, start=1):
        ws.cell(row=i, column=1, value=a)
        ws.cell(row=i, column=2, value=b)

    # bold the Total row so it stands out
    if len(rows_keep) > 1:
        total_row = len(rows_keep)
        for c in (1, 2):
            cell = ws.cell(row=total_row, column=c)
            f = cell.font
            cell.font = Font(
                name=f.name, size=f.size, bold=True, italic=f.italic,
                vertAlign=f.vertAlign, underline=f.underline, strike=f.strike,
                color=f.color, family=f.family, scheme=f.scheme
            )

    # delete trailing empty rows beyond rows_keep
    for r in range(ws.max_row, len(rows_keep), -1):
        ws.delete_rows(r, 1)

def apply_workbook_formatting(wb):
    yellow = PatternFill(start_color='FFFF00', end_color='FFFF00', fill_type='solid')
    center = Alignment(horizontal='center', vertical='center', wrap_text=False)
    thin   = Side(border_style='thin', color='000000')
    border = Border(left=thin, right=thin, top=thin, bottom=thin)

    for sn in wb.sheetnames:
        ws = wb[sn]
        if ws.max_row == 0 or ws.max_column == 0:
            continue

        # add Note column (skip Summary)
        if sn.lower() != "summary":
            # only add if not already present
            existing = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column+1)]
            if 'Note' not in existing:
                add_note_column(ws)

        # alignment + borders on all used cells
        for r in range(1, ws.max_row + 1):
            for c in range(1, ws.max_column + 1):
                cell = ws.cell(row=r, column=c)
                cell.alignment = center
                cell.border = border

        # yellow + bold + size+1 on header
        for c in range(1, ws.max_column + 1):
            cell = ws.cell(row=1, column=c)
            cell.fill = yellow
            f = cell.font
            size = f.size if f.size else 11
            cell.font = Font(
                name=f.name, size=size + 1, bold=True, italic=f.italic,
                vertAlign=f.vertAlign, underline=f.underline, strike=f.strike,
                color=f.color, family=f.family, scheme=f.scheme
            )

        # auto-filter
        last_col = get_column_letter(ws.max_column)
        ws.auto_filter.ref = f"A1:{last_col}{ws.max_row}"

        # uniform row height
        for r in range(1, ws.max_row + 1):
            ws.row_dimensions[r].height = 22

        # column widths sized to content (cap 60)
        for c in range(1, ws.max_column + 1):
            col_letter = get_column_letter(c)
            max_len = max((len(str(ws.cell(row=r, column=c).value or "")) for r in range(1, ws.max_row+1)), default=10)
            ws.column_dimensions[col_letter].width = min(max(max_len + 2, 10), 60)

        # default freeze: header row
        ws.freeze_panes = 'A2'

    # per-sheet freeze overrides
    s = find_sheet(wb, "Optic Errors", "Optic Errors (GPU)")
    if s: wb[s].freeze_panes = 'B2'   # freeze header + Rx Power (col A)
    s = find_sheet(wb, "FEC_BER Errors (GPU)")
    if s: wb[s].freeze_panes = 'B2'   # freeze header + Issue (col A)
    s = find_sheet(wb, "LLDP missing (IGNORE)", "LLDP Missing (GPU)", "LLDP Missing  (GPU)")
    if s: wb[s].freeze_panes = 'B2'   # freeze header + Error Message (col A)


# ---------------------------------------------------------------------------
# Mismatch reciprocal-pair grouping + highlight
# ---------------------------------------------------------------------------

def highlight_mismatch_pairs(wb):
    """On the LLDP Mismatch (GPU) tab, group reciprocal swap pairs + highlight.

    Two rows are a *pair* when one row's actual neighbour (Current Device B
    Name + Port) is exactly the other row's intended neighbour (Expected
    Device B Name + Port) AND vice-versa — i.e. the two links are crossed
    (each took the other's destination).

    Behaviour mirrors the FAB/CFAB formatters:
      • paired rows are grouped together (partner inserted directly beneath),
      • each pair's white (Expected-side) block is filled, alternating 1st
        pair orange, 2nd pair yellow, 3rd orange, …  (Current cols stay pink),
      • rows with no pair are pushed to the bottom with no highlight.
    """
    sheet = find_sheet(wb, "Mismatch", "LLDP Mismatch  (GPU)", "LLDP Mismatch (GPU)",
                       "LLDP Mismatch + Link Down (GPU)")
    if not sheet:
        return
    ws = wb[sheet]
    if ws.max_row < 3:
        return

    header = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column + 1)]

    def col(name):
        return header.index(name) + 1 if name in header else None

    exp_name = col('Expected Device B Name')
    exp_port = col('Expected Device B Port')
    cur_name = col('Current Device B Name')
    cur_port = col('Current Device B Port')
    if not all((exp_name, exp_port, cur_name, cur_port)):
        return

    pink_cols  = [i + 1 for i, h in enumerate(header) if 'current' in str(h).lower()]
    start_pink = min(pink_cols) if pink_cols else ws.max_column + 1
    white_cols = set(range(1, start_pink))     # colour these on paired rows
    pink_set   = set(pink_cols)                # stay pink

    ncol, nrow = ws.max_column, ws.max_row
    rows = [[ws.cell(row=r, column=c).value for c in range(1, ncol + 1)]
            for r in range(2, nrow + 1)]

    exp_keys = [(norm(rv[exp_name - 1]), norm(rv[exp_port - 1])) for rv in rows]
    cur_keys = [(norm(rv[cur_name - 1]), norm(rv[cur_port - 1])) for rv in rows]

    n = len(rows)
    partner = [None] * n
    for i in range(n):
        if partner[i] is not None or not any(exp_keys[i]):
            continue
        for j in range(i + 1, n):
            if partner[j] is not None:
                continue
            if cur_keys[i] == exp_keys[j] and cur_keys[j] == exp_keys[i]:
                partner[i] = j
                partner[j] = i
                break

    # Pairs first (partner directly beneath its match), unpaired at the end.
    placed = [False] * n
    order = []
    for i in range(n):
        if placed[i] or partner[i] is None:
            continue
        j = partner[i]
        order.append(i); placed[i] = True
        if not placed[j]:
            order.append(j); placed[j] = True
    for i in range(n):
        if not placed[i]:
            order.append(i); placed[i] = True

    paired = {i for i in range(n) if partner[i] is not None}

    # Number pairs in order of first appearance for alternating colours.
    pair_no, counter = {}, 0
    for i in range(n):
        j = partner[i]
        if j is not None and i < j:
            pair_no[i] = counter
            pair_no[j] = counter
            counter += 1

    orange = PatternFill(start_color='FFA500', end_color='FFA500', fill_type='solid')
    yellow = PatternFill(start_color='FFFF00', end_color='FFFF00', fill_type='solid')
    pink   = PatternFill(start_color='FFC0CB', end_color='FFC0CB', fill_type='solid')
    nofill = PatternFill(fill_type=None)

    for out_off, src_i in enumerate(order):
        r = out_off + 2
        rv = rows[src_i]
        is_pair = src_i in paired
        pair_fill = orange if pair_no.get(src_i, 0) % 2 == 0 else yellow
        for c in range(1, ncol + 1):
            cell = ws.cell(row=r, column=c, value=rv[c - 1])
            if c in pink_set:
                cell.fill = pink
            elif is_pair and c in white_cols:
                cell.fill = pair_fill
            else:
                cell.fill = nofill


# ---------------------------------------------------------------------------
# Output filename
# ---------------------------------------------------------------------------

def extract_rack_number(wb):
    racks = set()
    for sn in wb.sheetnames:
        ws = wb[sn]
        header = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column+1)]
        for ci, h in enumerate(header, start=1):
            if h and str(h).strip().lower().startswith('racka'):
                for r in range(2, ws.max_row + 1):
                    v = ws.cell(row=r, column=ci).value
                    if v:
                        m = re.search(r'Rack\s+(\d+)', str(v))
                        if m: racks.add(m.group(1))
    return sorted(racks)


# ---------------------------------------------------------------------------
# Main per-file pipeline
# ---------------------------------------------------------------------------

def process_one(input_path, combined):
    print(f"\n▶ {os.path.basename(input_path)}")
    wb = load_workbook(input_path)

    # per-sheet transformations
    s = process_lldp(wb, combined);              print(f"  • LLDP            -> {s}")
    s = process_lldp_missing(wb, combined);      print(f"  • LLDP Missing    -> {s}")
    s = process_optic(wb, combined);             print(f"  • Optic Errors    -> {s}")
    s = process_fec(wb, combined);               print(f"  • FEC_BER         -> {s}")
    s = process_rawber(wb, combined);            print(f"  • RAW_BER         -> {s}")
    s = process_interface_down(wb, combined);    print(f"  • Interface Down  -> {s}")

    # Summary refresh
    update_summary(wb)

    # workbook-wide formatting (must run AFTER all column ops)
    apply_workbook_formatting(wb)

    # group reciprocal mismatch pairs + highlight (after formatting)
    highlight_mismatch_pairs(wb)

    # output filename from rack numbers
    racks = extract_rack_number(wb)
    fname = ("-".join(racks) if racks else os.path.splitext(os.path.basename(input_path))[0]) + ".xlsx"
    out_dir = os.path.dirname(os.path.abspath(input_path))
    out_path = os.path.join(out_dir, fname)
    # if collision, append (1), (2), ...
    base, ext = os.path.splitext(out_path)
    n = 1
    while os.path.exists(out_path) and os.path.abspath(out_path) != os.path.abspath(input_path):
        out_path = f"{base} ({n}){ext}"
        n += 1

    wb.save(out_path)
    print(f"  ✓ saved: {out_path}")
    return out_path


# ---------------------------------------------------------------------------
# Streamlit-friendly entry point (added for the project, logic above is exact)
# ---------------------------------------------------------------------------

def format_report(validation_path: str, combined_path: str) -> str:
    """Exact port of the reference core logic for Streamlit use.

    Processes a single validation result file against the combined cutsheet.
    Returns the path to the formatted .xlsx (saved next to the input in the
    caller's temp directory).
    """
    combined = build_combined_lookups(combined_path)
    return process_one(validation_path, combined)
